### ISSUE TITLE
Lists - unreadable black elements in Dark mode

### ISSUE THREAD

**Issue by alorence** [piccolo-orm/piccolo_theme#20]
Hello,

It seems the Dark mode is not fully readable with some HTML elements. As an example, various kind of lists (Definition list, Option list, Field list, etc.) are rendered with a black main item in Dark mode. See an example here: https://sphinx-themes.org/sample-sites/piccolo-theme/kitchen-sink/lists/#field-list

![image](https://user-images.githubusercontent.com/1702273/157210097-72bff846-55eb-43e7-9ce0-9c6536f7214a.png)

**Comment by dantownsend** [comment]
@alorence Thanks - good catch!

I'll add an extra style for `dt` tags.

**Comment by dantownsend** [comment]
I've pushed the fixes to PyPI - hopefully should fix the problem.

I think sphinx-themes.org rebuilds daily, so hopefully will appear on there soon.

Thanks again 👍

**Comment by alorence** [comment]
Thanks ! I will try as soon as possible ;)

As far as I know, sphinx-theme rebuilds weekly

> This sample documentation was generated on Mar 07, 2022, and is rebuilt weekly.

From https://sphinx-themes.org/sample-sites/piccolo-theme/

I think the whangs will be visible next monday
