### ISSUE TITLE
Dark/Light mode issue in code block

### ISSUE THREAD

**Issue by sinus-x** [piccolo-orm/piccolo_theme#22]
Hi. My system is configured to use dark mode by default:

![image](https://user-images.githubusercontent.com/14353790/157838270-210e49e0-c355-4d6e-a182-0d2485637a3e.png)

But when I flip to the white theme, the text contained in the code block does not stay white:

![image](https://user-images.githubusercontent.com/14353790/157838430-6cb8ea61-8a30-4511-a0c0-76a8edba7804.png)

and it only affects the non-colored text:

![image](https://user-images.githubusercontent.com/14353790/157838963-7a44c569-16bc-4474-8e26-de2006d56509.png)

I'm using the latest `piccolo-theme-0.5.1`. I really like this theme, you've done a great job.

**Comment by dantownsend** [comment]
@sinus-x Thanks for reporting this issue. Are you using the default Pygments theme, or something custom?

Do you have the same issue in version 0.5.0? I released version 0.5.1 a few days ago with some CSS changes - just wondering if that might've been the cause.

**Comment by dantownsend** [comment]
Sorry, forgot to ask which browser and OS you're using?

**Comment by sinus-x** [comment]
Yeah, I had `stata-dark` Pygments theme enabled. When I commented out the line in config, everything is displayed properly.

![image](https://user-images.githubusercontent.com/14353790/157887319-3744eaa4-eb6b-4378-bcfd-9c6aececc829.png)

It is reproducible on both 0.5.0 and 0.5.1. My current Firefox version is 97.0.2 on Ubuntu 20.04.

**Comment by dantownsend** [comment]
Cool, thanks.

I think I know what the issue is. It's this line:

https://github.com/piccolo-orm/piccolo_theme/blob/b25d43bd70c77c1f09917ff6ee09af32e475b8fb/src/sass/basic_mod.scss#L280

It's overriding your Pygments font colour, making it black on black.

I'll try removing that line. Or somehow detect if a custom Pygments theme has been specified, and in that case won't override the CSS.

**Comment by dantownsend** [comment]
Should be fixed now by https://github.com/piccolo-orm/piccolo_theme/pull/38
