### ISSUE TITLE
pypi: no matching distribution found

### ISSUE THREAD

**Issue by oncilla** [piccolo-orm/piccolo_theme#32]
Hi. First of all thank you for this great theme. It looks great.

I was trying to install the theme with pip, but I cannot manage to.
Even though the theme is advertised on pypi https://pypi.org/project/piccolo-theme/0.9.0/, it seems that it is not registered correctly.

To recreate, run the following:

```
$ python3 -m venv /tmp/env
$ source /tmp/env/bin/activate

# As listed on pypi
$ pip install piccolo-theme==0.9.0
Collecting piccolo-theme==0.9.0
  Could not find a version that satisfies the requirement piccolo-theme==0.9.0 (from versions: )
No matching distribution found for piccolo-theme==0.9.0

# As listed in https://piccolo-theme.readthedocs.io/en/latest/setup.html#install-piccolo-theme
$ pip install piccolo_theme  
Collecting piccolo_theme
  Could not find a version that satisfies the requirement piccolo_theme (from versions: )
No matching distribution found for piccolo_theme
```

**Comment by dantownsend** [comment]
@oncilla How strange - what system are you on?

I wonder if PyPI was having a technical issue? I can install it OK on my Mac.

**Comment by oncilla** [comment]
I'm running on an older system: ubuntu 18.04

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

```
(env) $ pip --version
pip 21.3.1 from /tmp/env/lib/python3.6/site-packages/pip (python 3.6)
(env) $ python --version
Python 3.6.9
```

**Comment by dantownsend** [comment]
@oncilla Thanks - I'll spin up a Docker container and will give it a go.

**Comment by dantownsend** [comment]
Ah, I bet the issue is the Python 3.6.

**Comment by dantownsend** [comment]
I don't have the Python 3.6 specifier in the setup.py.

<img width="240" alt="Screenshot 2022-05-02 at 09 02 49" src="https://user-images.githubusercontent.com/350976/166203344-6210b7e2-cc15-42e5-8fa4-11274e20433c.png">
 
I think it should work OK on Python 3.6. I'll add that specifier.

**Comment by oncilla** [comment]
@dantownsend alright. :crossed_fingers: that was it.

By the way, I really appreciate the responsiveness. Thank you!

**Comment by dantownsend** [comment]
@oncilla No worries - I've pushed a new version now.

I managed to get it working, on Python 3.6.9, Pip 21.3.1, and Ubuntu 18.04.6:

```
pip install piccolo-theme==0.10.1
```

Does it work for you?

**Comment by shitz** [comment]
Hi @dantownsend 

Unfortunately, `__future__ annotations` is only available from Python 3.7...

```
  File "/home/sam/.local/lib/python3.6/site-packages/piccolo_theme/__init__.py", line 1
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined
```

**Comment by dantownsend** [comment]
@shitz Ah, good catch - I can remove that.

**Comment by dantownsend** [comment]
There's a new version on PyPI now:

```
pip install piccolo-theme==0.10.2
```

🤞

**Comment by shitz** [comment]
Works like a charm now, thanks a lot @dantownsend !

**Comment by dantownsend** [comment]
@shitz Awesome, mystery solved!
