### ISSUE TITLE
Code emphasis color in dark modes is not set - poor contrast.

### ISSUE THREAD

**Issue by amykyta3** [piccolo-orm/piccolo_theme#48]
I love the theme and am considering switching to it for a few of my projects!

One minor issue - it looks like the background color for emphasized code (HTML class `hll`) is not being overridden for dark modes. This results in some poor contrast.

For example:
![image](https://user-images.githubusercontent.com/12021539/225208307-be608da3-de1a-4875-b4cd-4e13cd182e22.png)

Compared to light mode:
![image](https://user-images.githubusercontent.com/12021539/225208410-7f42b338-d1c0-457d-927e-d33d61f2a284.png)

**Comment by dantownsend** [comment]
@amykyta3 Good catch. I've created a PR (https://github.com/piccolo-orm/piccolo_theme/pull/49) which makes the contract more subtle. What do you think about that?

**Comment by amykyta3** [comment]
Looks great!

**Comment by dantownsend** [comment]
@amykyta3 Cool - I've released it (`piccolo_theme==0.15.0`).
