### ISSUE TITLE
fonts.googleapis.com alternative

### ISSUE THREAD

**Issue by ThijsSassen** [piccolo-orm/piccolo_theme#56]
When using the theme within China we noticed that fonts.googleapis.com is not working. Would it be possible for this theme not to use this url but include the font inside the theme like also is done for the default themes within mkdocs. see also https://github.com/mkdocs/mkdocs/issues/1138

**Comment by dantownsend** [comment]
We can bundle the fonts in with the static files of the theme.

https://fonts.google.com/knowledge/using_type/self_hosting_web_fonts

The font we use is Roboto, which has a very flexible license, so distributing it along with the Piccolo theme shouldn't be a problem.

**Comment by Natureshadow** [comment]
I would very much like to use this theme, but as it stands, it is not compliant with widely accepted privacy basics.

Bundling the font would thus be much appreciated!

**Comment by noxpardalis** [comment]
> We can bundle the fonts in with the static files of the theme.
> 
> https://fonts.google.com/knowledge/using_type/self_hosting_web_fonts
> 
> The font we use is Roboto, which has a very flexible license, so distributing it along with the Piccolo theme shouldn't be a problem.

I opened a PR for this that implements your suggestion. I like the theme so it'll be nice if the privacy concerns of using this theme due to tracking from the Google fonts can be obviated.

**Comment by dantownsend** [comment]
Resolved by https://github.com/piccolo-orm/piccolo_theme/pull/57

**Comment by ThijsSassen** [comment]
@noxpardalis thanks! @dantownsend are there any plans for a new release with this feature?

**Comment by dantownsend** [comment]
@ThijsSassen Just did a release - should be available now in 0.16.0 👍
