### ISSUE TITLE
Mathjax overlaps sidebar on mobile

### ISSUE THREAD

**Issue by sasmlange** [piccolo-orm/piccolo_theme#63]
When opening the navigation menu on a mobile device, Mathjax overlaps the sidebar causing the sidebar to become unreadable. 

Example:
<img width="402" alt="Screen Shot 2023-09-20 at 12 23 18 PM" src="https://github.com/piccolo-orm/piccolo_theme/assets/68520673/500a518c-f39d-4edf-ac0f-c55c3d18839f">

**Comment by dantownsend** [comment]
@sasmlange It must be something to do with the z-index on the sidebar.

I've created a PR which should fix it 🤞

**Comment by dantownsend** [comment]
@sasmlange Try `piccolo_theme==0.18.0` - hopefully it fixes the issue. Make sure you clear your browser cache, as it's a CSS change.
