### ISSUE TITLE
Feature request: Prevent sidebar collapse label:enhancement

### ISSUE THREAD

**Issue by dem1995** [piccolo-orm/piccolo_theme#67]
Current situation: pages a level or more down in the Table of Contents are hidden unless viewed. 

Feature request: configuration setting to show leaf-level table-of-contents entries by default (or n levels down)

Example user-facing implementation:
In conf.py,
html_theme_options = {
   'toc_auto_minimize': True/False
   //or
   'toc_auto_minimize_level': 0 //default of zero
}

**Comment by dantownsend** [comment]
Yeah, I see what you mean. I agree this would be useful. There's an example of it [here](https://piccolo-orm.readthedocs.io/en/latest/piccolo/projects_and_apps/index.html).

<img width="235" alt="Screenshot 2023-11-15 at 22 02 25" src="https://github.com/piccolo-orm/piccolo_theme/assets/350976/2bb2cfae-cf33-4b19-84b7-a9d96180510a">

**Comment by dantownsend** [comment]
Turns out this is already possible:

```python
html_theme_options = {
    "globaltoc_collapse": False
}
```

I'll add this to the docs.
