### ISSUE TITLE
Piccolo doesn't have appropriate CSS for list styles

### ISSUE THREAD

**Issue by fizbin** [piccolo-orm/piccolo_theme#70]
When I have this in my source file:

```
1. Top-level
   a. second level
   b. second item second level
2. Second top level thing
   a. second second level
   b. second item second level
```

The intent is that in the rendered HTML I see uses numbers for the outermost list and lowercase letters in the second-level list.

The generated HTML has `<ol class="arabic simple">` on the top-level list and `<ol class="loweralpha simple">` on the second-level list.

If I use a style based on `basic.css`, those classes on the `<ol>` element result in the appropriate list-style being applied. However, using piccolo's `basic_mod.css`, the list-style CSS rules aren't applied, and in the rendered HTML all levels of the list use numbers.

**Comment by dantownsend** [comment]
I see what you mean. I'll have a play around with it.
