### ISSUE TITLE
Add `Used By` section to `README`

### ISSUE THREAD

**Issue by jrycw** [piccolo-orm/piccolo_theme#75]
@dantownsend , I recently noticed that [Lance](https://lancedb.github.io/lance/) is using this theme on their website. Do you think it would be beneficial to include a `Used By` section in the `README` to showcase the projects using our theme?

**Comment by dantownsend** [comment]
@jrycw That's a good idea.

Here are a couple of others I've seen:

* https://cyclonedds.io/docs/cyclonedds-python/latest/
* https://bitstring.readthedocs.io/en/stable/#

Would you like to create a PR?

**Comment by jrycw** [comment]
I'll go ahead and close this issue as it has been addressed by #76.
