### ISSUE TITLE
Sphinx 7.3: Quick search header is not hidden -> Header too big and hides main menu

### ISSUE THREAD

**Issue by heuer** [piccolo-orm/piccolo_theme#77]
Sphinx 7.3.x seems to have changed the syntax from ``<div id="searchbox" […]>`` to ``<search id="searchbox" […]`` which is not covered by Piccolo's CSS/SASS. The header's height becomes too big an therefor hides parts of the menu.

![2024-05-15_14-10](https://github.com/piccolo-orm/piccolo_theme/assets/364926/0a31d1bf-dbf0-4af1-bd78-b29599f3d4ab)
![2024-05-15_14-11](https://github.com/piccolo-orm/piccolo_theme/assets/364926/6ba345f9-f1c0-4c38-9941-5e4a253621f6)

I think the following line 

https://github.com/piccolo-orm/piccolo_theme/blob/e22f783e040a9edfb66c97ad25257ae339670f95/src/sass/basic_mod.scss#L150

has to be modified to something like

```sass
search#searchbox,
div#searchbox {
[…]
}
```

or just ``#searchbox``?

**Comment by dantownsend** [comment]
@heuer Good catch! I'll throw up a quick PR to fix it. I'll just use `#searchbox` in the CSS.

**Comment by dantownsend** [comment]
@heuer It should be fixed in `piccolo_theme==0.22.0` on PyPI. Thanks
