### ISSUE TITLE
Blue color of dark-mode code-block

### ISSUE THREAD

**Issue by superstes** [piccolo-orm/piccolo_theme#83]
Greetings.

For users that have dark mode on and a blue-light filter active, the blue color of the code-block (for variables) is invisible.

It's a pretty dark blue - maybe a lighter one will have a little more contrast?
Is there a way I can modify this color?

**Comment by dantownsend** [comment]
Like `__name__` in the screenshot below?

<img width="439" alt="Screenshot 2024-08-25 at 09 31 13" src="https://github.com/user-attachments/assets/b45e86ed-b07f-4f34-ad69-5d6baf650b23">

I see what you're saying - it is pretty dark.

How's this?

<img width="429" alt="Screenshot 2024-08-25 at 09 36 39" src="https://github.com/user-attachments/assets/b652237c-880d-4608-b225-4d8320e7a8e0">

The syntax highlighting uses two different shades of blue - so it's quite tricky making them both differentiated enough, but still visible on dark backgrounds.

We could just use something other than blue.

**Comment by dantownsend** [comment]
I've added a PR which lightens the shade of blue, it's easy enough to tweak it further though.

**Comment by superstes** [comment]
Yeah - the second shade of blue is visible and ok to see
Thank you 👍

**Comment by dantownsend** [comment]
OK, cool - will merge that in. Can always tweak in the future.
