### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by dantownsend** [piccolo-orm/piccolo_theme#9]
A simple toggle switch in the header or footer.

**Comment by dantownsend** [comment]
@flying-sheep Good point - that's a much better approach.

**Comment by flying-sheep** [comment]
In the furo theme, it’s solved like this:

- js: https://github.com/pradyunsg/furo/blob/9534e33cec40f5e004eb625285e1e902b8b8a752/src/furo/assets/scripts/furo.js#L84-L107
- css: https://github.com/pradyunsg/furo/blob/9534e33cec40f5e004eb625285e1e902b8b8a752/src/furo/assets/styles/base/_theme.sass#L16-L38

**Comment by dantownsend** [comment]
@flying-sheep Thanks, I'll take a look!

**Comment by dantownsend** [comment]
Dark mode has been implemented in v0.3.0 - it's on PyPI.

@flying-sheep thanks for those links, they were useful. If you have any feedback on the new dark mode, let me know. 🙏

**Comment by dantownsend** [comment]
@flying-sheep Thanks!
